'use client';
import { useAppStore, type HubProduct } from '@/store/app-store';
import { useTranslations } from '@/providers/use-translations';
import { JaminoAvatar } from '@/components/jamino-avatar';
import { TopRightControls } from '@/components/top-controls';
import { ArrowLeft, ArrowRight, Bird, Clapperboard, House, Music2, PlaySquare, UsersRound } from 'lucide-react';
import type { ReactNode } from 'react';
import { GlobalSearch } from '@/components/global-search';
import { NowFeed } from '@/components/now-feed';
import { LiveStatus } from '@/components/live-status';
const HUBS: { id: Exclude<HubProduct, 'home'>; icon: typeof Music2; tone: string; titleKey: string; descriptionKey: string }[] = [
  { id: 'community', icon: UsersRound, titleKey: 'community', descriptionKey: 'communityDesc', tone: 'community' },
  { id: 'music', icon: Music2, titleKey: 'music', descriptionKey: 'musicDesc', tone: 'music' },
  { id: 'video', icon: PlaySquare, titleKey: 'video', descriptionKey: 'videoDesc', tone: 'video' },
  { id: 'watch', icon: Clapperboard, titleKey: 'watch', descriptionKey: 'watchDesc', tone: 'watch' },
  { id: 'tweet', icon: Bird, titleKey: 'tweet', descriptionKey: 'tweetDesc', tone: 'tweet' },
];
export function WorkspaceTopbar({ onHome, product, children }: { onHome?: () => void; product?: string; children?: ReactNode }) { const me = useAppStore((state) => state.me); const t = useTranslations();     const labels: Record<string, string> = { 'Music Hub': t('hubs.music'), 'Video Hub': t('hubs.video'), 'Cinema Hub': t('hubs.cinema'), 'Anime Hub': t('hubs.anime'), 'Watch Hub': t('hubs.watch'), 'Tweet Hub': t('hubs.tweet'), 'Community Hub': t('hubs.community') }; return <div className="topbar hub-topbar"><button className="wordmark" onClick={onHome} style={{ background: 'none', border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 8 }}><span className="wordmark-mark"><House size={16} /></span>{t('brand.name')}</button><div className="hub-topbar-center">{(product && labels[product]) || product || t('hubs.choose')}</div><div className="tb-right"><GlobalSearch /><LiveStatus />{children}<TopRightControls inline /><div className="user-chip">{me && <JaminoAvatar avatarId={me.avatarId} size={32} photo={me.avatarPhoto} name={me.username} />}{me && <span className="friend-name" style={{ fontSize: 14 }}>{me.username}</span>}</div></div></div>; }
export function HubGateway() { const t = useTranslations(); const setProduct = useAppStore((state) => state.setProduct); const me = useAppStore((state) => state.me); return <div className="hub-shell"><WorkspaceTopbar product={t('hubs.choose')} /><main className="hub-gateway-content"><div className="hub-kicker">{t('brand.name').toUpperCase()} WORKSPACE</div><h1>{t('hubs.where')}</h1><p className="hub-lead">{t('hubs.lead')}</p><div className="hub-card-grid">{HUBS.map(({ id, icon: Icon, titleKey, descriptionKey, tone }) => <button type="button" className={`hub-card hub-card-${tone}`} key={id} onClick={() => setProduct(id)}><span className="hub-card-icon"><Icon size={26} /></span><span className="hub-card-copy"><strong>{t(`hubs.${titleKey}`)}</strong><span>{t(`hubs.${descriptionKey}`)}</span></span><ArrowRight className="hub-card-arrow" size={18} /></button>)}</div>{me && <div className="hub-account-note">{t('hubs.signed')} <b>@{me.username}</b>. {t('hubs.accountNote')}</div>}{me && <NowFeed />}</main></div>; }
export function EmptyHub({ kind }: { kind: 'music' | 'video' }) { const t = useTranslations(); const setProduct = useAppStore((state) => state.setProduct); const music = kind === 'music'; return <div className={`hub-shell hub-shell-${kind}`}><WorkspaceTopbar onHome={() => setProduct('home')} product={t(`hubs.${music ? 'music' : 'video'}`)} /><main className="hub-empty-content"><button type="button" className="hub-back" onClick={() => setProduct('home')}><ArrowLeft size={15} /> {t('hubs.all')}</button><div className="hub-empty-icon">{music ? <Music2 size={34} /> : <PlaySquare size={34} />}</div><div className="hub-kicker">{t(`hubs.${music ? 'music' : 'video'}`).toUpperCase()}</div><h1>{t(`hubs.${music ? 'musicReady' : 'videoReady'}`)}</h1><p>{t(`hubs.${music ? 'musicDescLong' : 'videoDescLong'}`)}</p><span className="hub-empty-badge">{t('hubs.coming')}</span></main></div>; }
