'use client';

import { ArrowDown, ArrowRight, Headphones, MessageCircle, PlaySquare, Sparkles, UsersRound } from 'lucide-react';
import { useAppStore } from '@/store/app-store';
import { useTranslations } from '@/providers/use-translations';
import { AuthScreen } from '@/components/auth-screen';
import { JamiMascot } from '@/components/jami-mascot';

export function LandingPage() {
  const t = useTranslations();
  const setAuthView = useAppStore((state) => state.setAuthView);
  const openAuth = (view: 'login' | 'signup') => { setAuthView(view); document.getElementById('landing-auth')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); };
  return <main className="landing-page">
    <nav className="landing-nav"><a className="landing-brand" href="#top" aria-label={t('landing.home')}><span className="wordmark-mark"><Sparkles size={15} /></span><span>Jamino</span></a><div className="landing-nav-links"><a href="#features">{t('landing.features')}</a><a href="#how-it-works">{t('landing.how')}</a><a href="#landing-auth">{t('landing.join')}</a></div><div className="landing-nav-actions"><button type="button" className="btn btn-ghost pill-sm" onClick={() => openAuth('login')}>{t('landing.login')}</button><button type="button" className="btn btn-violet pill-sm" onClick={() => openAuth('signup')}>{t('landing.create')}</button></div></nav>
    <section className="landing-hero" id="top"><div className="landing-hero-copy"><div className="landing-kicker"><span className="landing-pulse" /> {t('landing.kicker')}</div><h1>{t('landing.hero')}</h1><p>{t('landing.intro')}</p><div className="landing-actions"><button type="button" className="btn btn-violet landing-cta" onClick={() => openAuth('signup')}>{t('landing.start')} <ArrowRight size={16} /></button><a className="landing-secondary-cta" href="#features"><span>{t('landing.explore')}</span><ArrowDown size={15} /></a></div><div className="landing-proof"><span className="landing-proof-avatars"><JamiMascot state="happy" size={30} /><JamiMascot state="chat" size={30} /><JamiMascot state="party" size={30} /></span><span>{t('landing.proof')}</span></div></div><div className="landing-hero-stage" aria-label={t('landing.preview')}><div className="landing-orbit landing-orbit-one" /><div className="landing-orbit landing-orbit-two" /><div className="landing-mascot-glow"><JamiMascot state="wave" size={270} /></div><div className="landing-float-card landing-float-card-top"><span className="landing-float-icon violet"><UsersRound size={15} /></span><div><b>{t('landing.private')}</b><small>{t('landing.privateHint')}</small></div><span className="landing-live-pill">{t('landing.live')}</span></div><div className="landing-float-card landing-float-card-bottom"><span className="landing-float-icon pink"><Headphones size={15} /></span><div><b>{t('landing.synced')}</b><small>{t('landing.syncedHint')}</small></div><span className="landing-eq"><i /><i /><i /><i /></span></div></div></section>
    <section className="landing-marquee" aria-label={t('landing.products')}><span>{t('landing.community')}</span><i /><span>{t('landing.music')}</span><i /><span>{t('landing.video')}</span><i /><span>{t('landing.cinema')}</span><i /><span>{t('landing.connected')}</span></section>
    <section className="landing-section" id="features"><div className="landing-section-heading"><div><div className="landing-kicker">{t('landing.built')}</div><h2>{t('landing.lessNoise')}</h2></div><p>{t('landing.featureIntro')}</p></div><div className="landing-card-grid"><article className="landing-feature-card landing-feature-violet"><div className="landing-card-number">01</div><span className="landing-feature-icon"><MessageCircle size={22} /></span><h3>{t('landing.rooms')}</h3><p>{t('landing.roomsDesc')}</p><span className="landing-card-link">{t('landing.community')} <ArrowRight size={14} /></span></article><article className="landing-feature-card landing-feature-pink"><div className="landing-card-number">02</div><span className="landing-feature-icon"><Headphones size={22} /></span><h3>{t('landing.musicSync')}</h3><p>{t('landing.musicDesc')}</p><span className="landing-card-link">{t('landing.music')} <ArrowRight size={14} /></span></article><article className="landing-feature-card landing-feature-blue"><div className="landing-card-number">03</div><span className="landing-feature-icon"><PlaySquare size={22} /></span><h3>{t('landing.creatorHome')}</h3><p>{t('landing.creatorDesc')}</p><span className="landing-card-link">{t('landing.video')} <ArrowRight size={14} /></span></article></div></section>
    <section className="landing-section landing-flow-section" id="how-it-works"><div className="landing-section-heading"><div><div className="landing-kicker">{t('landing.flow')}</div><h2>{t('landing.flowTitle')}</h2></div><p>{t('landing.flowIntro')}</p></div><div className="landing-flow-grid"><div className="landing-flow-card"><strong>01</strong><JamiMascot state="idle" size={86} /><div><h3>{t('landing.find')}</h3><p>{t('landing.findDesc')}</p></div></div><div className="landing-flow-card"><strong>02</strong><JamiMascot state="wave" size={86} /><div><h3>{t('landing.energy')}</h3><p>{t('landing.energyDesc')}</p></div></div><div className="landing-flow-card"><strong>03</strong><JamiMascot state="party" size={86} /><div><h3>{t('landing.channel')}</h3><p>{t('landing.channelDesc')}</p></div></div></div></section>
    <section className="landing-auth-section" id="landing-auth"><div className="landing-auth-copy"><div className="landing-kicker">{t('landing.waiting')}</div><h2>{t('landing.bring')}</h2><p>{t('landing.authIntro')}</p><div className="landing-auth-note"><Sparkles size={15} /><span>{t('landing.authNote')}</span></div></div><div className="landing-auth-card"><AuthScreen /></div></section>
    <footer className="landing-footer"><span>© 2026 Jamino</span><span>{t('landing.footer')}</span><a href="#top">{t('landing.back')} ↑</a></footer>
  </main>;
}
