import { handle, json, err, requireAdmin } from '@/lib/api';
import { prisma } from '@/lib/prisma';
import { pushAdminEvent } from '@/lib/admin';
function safeJson(raw: unknown, fallback = '[]') { if (Array.isArray(raw)) return JSON.stringify(raw); if (typeof raw === 'string') { try { const value = JSON.parse(raw); return JSON.stringify(Array.isArray(value) ? value : JSON.parse(fallback)); } catch {} } return fallback; }
function parse(item: any) { return { ...item, genres: JSON.parse(item.genres || '[]'), chapterCount: item._count?.chaptersList ?? 0 }; }
export const GET = handle(async (req: Request) => { await requireAdmin(); const params = new URL(req.url).searchParams; const kind = params.get('kind')?.toUpperCase(); const where = kind === 'ANIME' || kind === 'MANGA' ? { kind } : {}; const items = await prisma.mediaCatalogItem.findMany({ where, orderBy: { updatedAt: 'desc' }, include: { _count: { select: { chaptersList: true } } } }); return json({ items: items.map(parse) }); });
export const POST = handle(async (req: Request) => { const me = await requireAdmin(); const body = await req.json().catch(() => ({})); const kind = String(body.kind || '').toUpperCase(); const title = String(body.title || '').trim(); const slug = String(body.slug || title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')).slice(0, 120); if (!['ANIME', 'MANGA'].includes(kind) || !title || !slug) return err('Kind, title and slug are required'); const existing = await prisma.mediaCatalogItem.findUnique({ where: { slug } }); if (existing) return err('Slug already exists', 409); const item = await prisma.mediaCatalogItem.create({ data: { kind, slug, title, original: String(body.original || '').slice(0, 200), synopsis: String(body.synopsis || '').slice(0, 5000), genres: safeJson(body.genres), coverUrl: String(body.coverUrl || '').slice(0, 1600), backdropUrl: String(body.backdropUrl || '').slice(0, 1600), studio: String(body.studio || '').slice(0, 160), status: String(body.status || 'ONGOING').toUpperCase(), year: Number(body.year || 0), score: Number(body.score || 0), episodes: Number(body.episodes || 0), chapters: Number(body.chapters || 0), featured: Boolean(body.featured), published: body.published !== false } }); pushAdminEvent('catalog', `Created ${kind.toLowerCase()} catalog item: ${title}`, { action: 'catalog-create', id: item.id, kind }); return json({ item: parse(item) }, 201); });
export const PATCH = handle(async (req: Request) => { const body = await req.json().catch(() => ({})); const id = Number(body.id); if (!Number.isInteger(id) || id <= 0) return err('Invalid catalog item'); const item = await prisma.mediaCatalogItem.update({ where: { id }, data: { title: body.title === undefined ? undefined : String(body.title).trim(), original: body.original === undefined ? undefined : String(body.original).slice(0, 200), synopsis: body.synopsis === undefined ? undefined : String(body.synopsis).slice(0, 5000), genres: body.genres === undefined ? undefined : safeJson(body.genres), coverUrl: body.coverUrl === undefined ? undefined : String(body.coverUrl).slice(0, 1600), backdropUrl: body.backdropUrl === undefined ? undefined : String(body.backdropUrl).slice(0, 1600), studio: body.studio === undefined ? undefined : String(body.studio).slice(0, 160), status: body.status === undefined ? undefined : String(body.status).toUpperCase(), year: body.year === undefined ? undefined : Number(body.year), score: body.score === undefined ? undefined : Number(body.score), episodes: body.episodes === undefined ? undefined : Number(body.episodes), chapters: body.chapters === undefined ? undefined : Number(body.chapters), featured: body.featured === undefined ? undefined : Boolean(body.featured), published: body.published === undefined ? undefined : Boolean(body.published) }, include: { _count: { select: { chaptersList: true } } } }); pushAdminEvent('catalog', `Updated catalog item: ${item.title}`, { action: 'catalog-update', id }); return json({ item: parse(item) }); });
export const DELETE = handle(async (req: Request) => { const body = await req.json().catch(() => ({})); const id = Number(body.id); if (!Number.isInteger(id) || id <= 0) return err('Invalid catalog item'); const item = await prisma.mediaCatalogItem.delete({ where: { id } }); pushAdminEvent('catalog', `Deleted catalog item: ${item.title}`, { action: 'catalog-delete', id }); return json({ deleted: true }); });
